### ISSUE TITLE
Convert to being 100% RPN-based.

### ISSUE THREAD

**Issue by skx** [skx/math-compiler#14]
Currently the input we parse is _like_ a reverse-polish stack-based calculator, but it is not reall.

We should make it such that we are, allowing input such as this: 

     1 2 3 4 5 6 7 8 9 10+++++++++
      (-> 55 )

This isn't a significant change, but could be improved by code-folding.  The biggest difficulty will be that we want to split the template we use for generating the program into distinct steps.

**Comment by mirimmad** [comment]
Any chance that you've read "Writing an Interpreter/Compiler in Go"?

**Comment by skx** [comment]
The former?  Yes.  The latter?  No.

That lead to [my version of monkey](http://github.com/skx/monkey/), and then later a [simple BASIC](http://github.com/skx/gobasic/).   I suspect that writing more languages is a bit pointless, but learning more about such things was useful as it let me update [my toy-deployment tool](https://github.com/skx/deployr) to be a bit more reliable.

I'll conclude my shameless self-promotion with this link to a [blog-post](https://blog.steve.fi/i_decided_it_was_time_to_write_a_compiler.html) I wrote earlier!
